### ISSUE TITLE
Best practice recommendations for snapshot file names

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#3252] opened 2023-04-24 16:48 UTC
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/build/snapshots

### What part(s) of the page would you like to see updated?

We should update this page to include our best practice recommendations for snapshot file names!

From @graciegoheen [here](https://github.com/dbt-labs/docs.getdbt.com/issues/3242):

> It’s our best practice for the name of the files to match the name of the snapshot, but our examples have names that differ from the snapshot name (this confused a customer i’m working with who was trying to copy the examples to test out the functionality)

**Comment by runleonarun** [comment] 2023-09-21 15:53
Closing as fixed in https://github.com/dbt-labs/docs.getdbt.com/pull/3251. Duplicate of #3242

**Closed as completed by runleonarun** 2023-09-21 15:53 UTC
Labels: content, improvement, priority: high, size: x-small
