### ISSUE TITLE
Incorrect docs for source freshness in 1.7

### ISSUE THREAD

**Issue by b-per** [fishtown-analytics/docs.getdbt.com#4718] opened 2024-01-08 10:31 UTC
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-properties/freshness

### What part(s) of the page would you like to see updated?

The docs for 1.7 mention the following

> Additionally, the loaded_at_field is required to calculate freshness for a table. If a loaded_at_field is not provided, then dbt will not calculate freshness for the table.

But since 1.7 `loaded_at_field` is not required anymore for all adapters (see [here](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.7#behavior-changes)). I don't think that it is the case for all adapters though, and I don't know which adapters require or not `loaded_at_field`. The adapter team might be able to help.

**Comment by runleonarun** [comment] 2024-01-18 01:19
Closing as duplicate of https://github.com/dbt-labs/docs.getdbt.com/issues/4615

**Closed as completed by runleonarun** 2024-01-18 01:19 UTC
Labels: content, improvement, source freshness
