### ISSUE TITLE
Loom videos erroring out on "Explore your dbt Projects" page

### ISSUE THREAD

**Issue by bbrewington** [fishtown-analytics/docs.getdbt.com#4829] opened 2024-01-30 19:04 UTC
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/docs/collaborate/explore-projects

Here's an example permalink to Loom video embed: https://github.com/dbt-labs/docs.getdbt.com/blob/0d36f6fc537698f2a8e32f0e78cbc5c622e23552/website/docs/docs/collaborate/explore-projects.md?plain=1#L74

### What changes are you suggesting?

Loom video embed that works

**Comment by nghi-ly** [comment] 2024-01-31 18:10
thanks for reporting, @bbrewington ! 

i just tested the embed video in this section https://docs.getdbt.com/docs/collaborate/explore-projects#project-lineage and it's working for me. I also checked https://www.loomstatus.com/ and no incidents over the past several days. 

is it still erroring out for you today? i'll also check around and see if it's working on other computers.

**Comment by amychen1776** [comment] 2024-02-28 22:07
All of the videos are working for me 🤔

**Comment by nghi-ly** [comment] 2024-02-29 17:54
hi @bbrewington , since we can't reproduce this atm, i'll go ahead and close this issue. please feel free to reopen!

**Closed as completed by nghi-ly** 2024-02-29 17:54 UTC
Labels: bug, engineering

**Comment by bbrewington** [comment] 2024-03-08 16:05
weird!  It's working now, so yep thanks for checking & closing
