### ISSUE TITLE
Mentioning 'dbt clean' doesn't work on Cloud in the Command ref page

### ISSUE THREAD

**Issue by nadjaljury** [fishtown-analytics/docs.getdbt.com#1103] opened 2022-02-10 00:57 UTC
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/commands/clean

### What part(s) of the page would you like to see updated?

I always forget that `dbt clean` isn't available on the Cloud IDE, and I spend ages trying to make it work and/or searching what it should be instead. It'd be amazing if there was a note on the Clean command reference page saying that it doesn't work on Cloud (and maybe that `dbt deps` will secretly do it behind the scenes).

**Comment by runleonarun** [comment] 2022-02-10 01:18
@nadjaljury This is such great feedback! Thank you! I will triage this to be addressed as soon as we can get to it, but you are also always welcome to open a PR. 🙇🏻‍♀️

**Comment by gwenwindflower** [comment] 2022-05-27 17:18
Duplicate of #618

**Closed as completed** 2022-05-27 17:50 UTC
Labels: content, improvement, priority: medium, size: x-small
