### ISSUE TITLE
version docs should include versioning

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#3314] opened 2023-05-01 20:43 UTC
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/project-configs/version

Doesn't have any mention of model versioning. 

### What part(s) of the page would you like to see updated?

Maybe it's a disambiguation callout ("you might be looking for [versions](https://docs.getdbt.com/reference/resource-properties/versions))?

**Comment by dbeatty10** [comment] 2023-05-01 20:58
@joellabes great minds think alike!

This looks like a duplicate of https://github.com/dbt-labs/docs.getdbt.com/issues/3290, so I'm going to close this proactively.

**Closed as not planned by dbeatty10** 2023-05-01 20:58 UTC
Labels: content, improvement
